version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb
  counter:
    restart: always
    build: ./counter
    privileged: true
  wifi:
    build: .
    privileged: true
    labels:
      io.balena.features.dbus: '1'
  i2c:
    build: ./i2c
    privileged: true
    labels: 
      io.balena.features.balena-api: '1'
      io.balena.features.kernel-modules: '1'